/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jframekash;

import java.awt.BorderLayout;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;
import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.hardware.NetworkIF;

/**
 *
 * @author vinicius
 */
public class TelaRede extends javax.swing.JFrame {

    private SystemInfo si = new SystemInfo();
    private HardwareAbstractionLayer hal = si.getHardware();
    private List<NetworkIF> redes = hal.getNetworkIFs();
    private ImageIcon img = new ImageIcon("src/main/resources/logoWhite.png");
    private Boolean isGraficoPacoteOnScreen = true;


    /**
     * Creates new form TelaRede
     */
    public TelaRede() {
        initComponents();

        img.setImage(img.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), 1));
        lblLogo.setIcon(img);

        printRede(redes);
        mostrarGraficoPacotes(redes);
    }

    private void printRede(List<NetworkIF> redes) {

        NetworkIF rede = redes.get(redes.size() - 1);

        String[] ipv4 = rede.getIPv4addr();
        String[] ipv6 = rede.getIPv6addr();
        
        lblIpv4.setText(lblIpv4.getText() + Arrays.deepToString(ipv4).replace("[", "").replace("]", ""));
        lblIpv6.setText(lblIpv6.getText() + Arrays.deepToString(ipv6).replace("[", "").replace("]", ""));
    }

    private void mostrarGraficoBanda(List<NetworkIF> redes) {

        NetworkIF rede = redes.get(redes.size() - 1);

        Long mbEnviados = rede.getBytesSent();
        Long mbRecebidos = rede.getBytesSent();

        mbEnviados = mbEnviados / 1024 / 1024;
        mbRecebidos = mbRecebidos / 1024 / 1024;

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.addValue(mbEnviados, "MB enviados", "MB enviados");
        dataset.addValue(mbRecebidos, "MB recebidos", "MB recebidos");

        JFreeChart chart = ChartFactory.createBarChart("", "", "", dataset);

        ChartPanel frame1 = new ChartPanel(chart);

        painelGrafico.removeAll();
        painelGrafico.add(frame1, BorderLayout.CENTER);
        painelGrafico.validate();

        jButton1.setText("Ver informações de pacotes");
        lblSubTitulo.setText("Informações de banda de rede");
        
        isGraficoPacoteOnScreen = false;
    }

    private void mostrarGraficoPacotes(List<NetworkIF> redes) {
        NetworkIF rede = redes.get(redes.size() - 1);

        Long pacotesEnviados = rede.getPacketsSent();
        Long pacotesRecebidos = rede.getPacketsRecv();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.addValue(pacotesEnviados, "Pacotes Enviados", "Pacotes Enviados");
        dataset.addValue(pacotesRecebidos, "Pacotes Recebidos", "Pacotes Recebidos");

        JFreeChart chart = ChartFactory.createBarChart("", "", "", dataset);

        ChartPanel frame1 = new ChartPanel(chart);

        painelGrafico.removeAll();
        painelGrafico.add(frame1, BorderLayout.CENTER);
        painelGrafico.validate();

        jButton1.setText("Ver informações de banda de rede");
        lblSubTitulo.setText("Informações sobre os pacotes");
        
        isGraficoPacoteOnScreen = true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblIpv4 = new javax.swing.JLabel();
        lblIpv6 = new javax.swing.JLabel();
        painelGrafico = new javax.swing.JPanel();
        btnProcessos = new javax.swing.JButton();
        btnTemp = new javax.swing.JButton();
        btnCPU = new javax.swing.JButton();
        btnDisco = new javax.swing.JButton();
        btnMemo = new javax.swing.JButton();
        btnSO12 = new javax.swing.JButton();
        lblSubTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoWhite.png"))); // NOI18N
        lblLogo.setAlignmentX(-18.0F);
        lblLogo.setAlignmentY(-200.0F);

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblTitulo.setText("Rede");

        lblIpv4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblIpv4.setText("IPv4: ");

        lblIpv6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblIpv6.setText("IPv6: ");

        painelGrafico.setLayout(new java.awt.BorderLayout());

        btnProcessos.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnProcessos.setText("Processos");
        btnProcessos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessosActionPerformed(evt);
            }
        });

        btnTemp.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnTemp.setText("Temperatura");
        btnTemp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempActionPerformed(evt);
            }
        });

        btnCPU.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnCPU.setText("CPU");
        btnCPU.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCPU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPUActionPerformed(evt);
            }
        });

        btnDisco.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnDisco.setText("Disco");
        btnDisco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscoActionPerformed(evt);
            }
        });

        btnMemo.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnMemo.setText("Memória");
        btnMemo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoActionPerformed(evt);
            }
        });

        btnSO12.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnSO12.setText("Sistema");
        btnSO12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSO12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSO12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSO12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSO12ActionPerformed(evt);
            }
        });

        lblSubTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSubTitulo.setText("Informações de pacote:");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Ver informaçãoes de banda de rede");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(lblIpv4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMemo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTemp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCPU, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProcessos, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIpv6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblSubTitulo)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(painelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSO12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDisco)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblTitulo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblIpv4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lblIpv6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(lblSubTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCPU)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisco)
                        .addGap(18, 18, 18)
                        .addComponent(btnSO12)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(painelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnProcessos)
                        .addGap(18, 18, 18)
                        .addComponent(btnTemp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessosActionPerformed
        TelaProcessos in = new TelaProcessos();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnProcessosActionPerformed

    private void btnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPUActionPerformed
        TelaCPU in = new TelaCPU();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnCPUActionPerformed

    private void btnDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscoActionPerformed
        TelaDisco in = new TelaDisco();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnDiscoActionPerformed

    private void btnMemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoActionPerformed
        TelaMemoria in = new TelaMemoria();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnMemoActionPerformed

    private void btnSO12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSO12ActionPerformed
        TelaSO in = new TelaSO();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnSO12ActionPerformed

    private void btnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempActionPerformed
        TelaTemperatura in = new TelaTemperatura();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnTempActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isGraficoPacoteOnScreen){
            mostrarGraficoBanda(redes);
        }
        else{
            mostrarGraficoPacotes(redes);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCPU;
    private javax.swing.JButton btnDisco;
    private javax.swing.JButton btnMemo;
    private javax.swing.JButton btnProcessos;
    private javax.swing.JButton btnSO12;
    private javax.swing.JButton btnTemp;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lblIpv4;
    private javax.swing.JLabel lblIpv6;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel painelGrafico;
    // End of variables declaration//GEN-END:variables
}
